### ISSUE TITLE
Add `stream_in` and `stream_out` to fs.rs

### ISSUE THREAD

**Issue by deg4uss3r** [killercup/quicli#36]
I love the command line because of how easy it is to chain commands together (really the only other thing as easy are Rust iterators ;)).

For example: 

`head Sherlock_Complete_Works.txt | rg -w '^Sherlock | less`

Adding the `stream_in` and `steam_out` fs.rs functions with `read_file` and `write_file` would reallly compliment this library for CLIs.

**Comment by killercup** [comment]
Hm, can you be a bit more specific in how you want stream_in and stream_out to work? I guess you want stdin/stdout to read from/write to what other tools write/read, but I'm not sure of the interface you want to have :)

**Comment by killercup** [comment]
Ah, I see! You want to have a command line flag for "file", if it's not set, read from stdin, i.e., what another program piped into yours? (And the same for output.)

This is something we can do! For input, you can use `input_file: Option<String>` flag. If it's `None`, you use [`std::io::stdin`](https://doc.rust-lang.org/nightly/std/io/fn.stdin.html), otherwise you go with `read_file`.

We can totally abstract over this, but I'm not sure how to do this in a _simple_ way: Instead of `String`s, you really want to use "buffered readers", because then you can process the data as it comes it (instead of reading all of it into a `String` and _then_ start working on the data).

For output, this is mostly the same, _except_ you have to be really careful not to use `println!` for reporting _anywere_, otherwise that gets forwarded to the next tool in the pipe-chain.
